version: '3'

services:
  web:
    build: .
    container_name: web
    command: daphne -b 0.0.0.0 -p 8000 main.asgi:application
    volumes:
      - .:/app  # Este volumen mapea el código fuente al contenedor
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/1  # Agrega la variable de entorno para Redis, si es necesario

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data  # El volumen persistirá los datos de Redis

volumes:
  redis_data:  # Define un volumen persistente para Redis
